GET http://127.0.0.1:8000/
###

GET http://127.0.0.1:8000/greet/John
###

GET http://127.0.0.1:8000/greet?name=John
# GET http://127.0.0.1:8000/greet
###

PUT http://127.0.0.1:8000/item/1
Content-Type: application/json

{
    "id" : 1,
    "name" : "Milk",
    "price" : 2.00,
    "description" : "nice milk",
    "on_offer" : false
}